### ISSUE TITLE
PSD File for Characters Image

### ISSUE THREAD

**Issue by Tekanewa** [zemax/jquery-splitFlap#2]
Hi,

I really love this little scripts and was wondering if it would be possible to get (if it exists) the .PSD file that was used to create the image that contains the characters. I was asked to potentially add a different alphabet (i.e. greek, russian, etc.).

Thank you!

Kalydon

**Comment by zemax** [comment]
Sure, I've added the 2 PSD I've used. (that's made-by-a-coder PSD, not sure they are re-usable).
I've used the Targa font for this demo as it's free for non-commercial use.

**Comment by Tekanewa** [comment]
Awesome!

Thank you so much! Once I created a new set for a different alphabet, I will add it here as well, so others can use it. :)

Kalydon
