### ISSUE TITLE
Problem with using  smaller characters 

### ISSUE THREAD

**Issue by ironbone** [zemax/jquery-splitFlap#3]
I'm not able to change the size of the characters. See for example what happens after using the following change in your example main.js

$('.empty-splitflap')
                .splitFlap({
                    text: 'This text was created from js',
                    charWidth: 20,
                    charHeight: 40
                }); 

The div is smaller but the characters have still the previous size. So I can see only parts of the characters.

**Comment by zemax** [comment]
The size parameters are here to match the size of the chars in the PNG.
You cannot change the size without changing the PNG

**Comment by ironbone** [comment]
So, I can understand. 
But I thing the script will be much flexible having only one set of characters in png. And additionally  two size parameters - the current size and the wanted size. Then resize the character using JS (or just use img tag parameters) and present the wanted size to the user.
I know it can be difficult and not so easy applicable to the current version, but much more useful.
I want for example use this script on a web page witch will be presented of devices with different size so at this moment I need to prepare different characters png. 
The solution can be also to set the the size in % up to the current hight of the div - I try to use your plug-in in joomla which just change the sizes of divs up to the current device size.

Sorry for the amount of remarks. I know it is not easy to implement it all now. But I realy like your script and I want to use it. 
Best regards

**Comment by zemax** [comment]
The problem is that the background size does not match the div size.
But you can easily correct that directly in CSS by settings the background-size of '.char > div' elements to match your resized background size.
Or you can resize the png.

**Comment by ironbone** [comment]
Thank you - this is clear

**Comment by tknman0700** [comment]
I am trying to understand how to resize the text... could you offer an explanation? I really dont want to size the png image or create new ones. Just trying to make smaller text using your animation.
Thanks

**Comment by zemax** [comment]
The module wasn't meant to have a fluid width, but you can initialise it at different sizes.
I've added a parameters to specify image Size and an example on how it can be used.

**Comment by ironbone** [comment]
Add please also the imageSize example values to the READ.me :). It can be not clear at this moment
